# Generated by Django 4.0.5 on 2022-06-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False)),
                ('has_reminder', models.BooleanField(default=False)),
                ('reminder_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
